---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
#  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[ruby_install::default]
    attributes:

  - name: install
    run_list:
      - recipe[ruby_install::install]
    attributes:
      ruby_install:
        rubies:
          - ruby: 'ruby 2.2.4'
            sha512: 'd27ca2f19c214ce87f906b57edd41f2f8af35b2871c191470facded9cfda15ba46e5c3bc7d5540225a38da6bd65050fcc8aaa4ffbadbb6bf7dc891c1821da0df'

          - ruby: 'ruby 2.3.0'
            sha256: 'ec7579eaba2e4c402a089dbc86c98e5f1f62507880fd800b9b34ca30166bfa5e'

          - ruby: 'jruby 1.7.24'
            md5: '295b41f5dc332fbc0e0a639d784cc30f'

          - ruby: 'ruby 2.1'
